### ISSUE TITLE
error while creating model

### ISSUE THREAD

**Issue by paulcx** [d-li14/regnet.pytorch#1]
```
from regnet import *

model = regnetx_320()
```

AttributeError: 'RegNet' object has no attribute 'bn3'

Is there any demo I can follow?

**Comment by d-li14** [comment]
It should have been fixed in the latest commit.

**Comment by paulcx** [comment]
It works now for sure. Thanks
btw, any plan to import the regnetY series (like creating interface for fb pretrained models)?

**Comment by d-li14** [comment]
@paulcx RegNetY merely inserts an SE module to RegNetX, for the FB version in this repository, you could simply set the argument `se_r` in [this line](https://github.com/d-li14/regnet.pytorch/blob/master/regnet_fb.py#L244); for the PyTorch version, you may manually add the SE module after `bn3`. Currently, pre-trained models (either trained by myself or converted from FB) are not in my plan.
